version: '3.8'

services:
  springboot:
    build:
      context: ./server
      dockerfile: Dockerfile-springboot
    container_name: springboot
    ports:
      - "4040:4040"
    env_file:
      - ./client/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  react:
    build:
      context: ./client
      dockerfile: Dockerfile-react
    container_name: react
    ports:
      - "3000:80"
    networks:
      - app-network

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
