# Use the official Gradle image to create a build artifact.
FROM gradle:7.5-jdk17 as build

# Set the working directory
WORKDIR /home/gradle/project

# Copy the project files
COPY --chown=gradle:gradle . .

# Build the project
RUN gradle build --no-daemon

# Use the official OpenJDK 17 runtime image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file from the build stage
#COPY --from=build /home/gradle/project/build/libs/your-spring-boot-app.jar app.jar
COPY --from=build /home/gradle/project/build/libs/*.jar /app/app.jar

# Expose the application port
EXPOSE 4040

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
